### ISSUE TITLE
需要紧急帮助🌝

### ISSUE THREAD

**Issue by xianquu** [luyii-code-1/rainyunautobat#1]
我是SFA战略司令官皇帝睿🌝也是仙区自由组织，资本主义青年团总官🌝

现在，军方正在对星火商店进行行动，星火商店是国产垃圾Debian商店，代码极差，是污染开源社区的，所以军方就轰炸了此商店🌝

但是，轰炸计划不顺利，敌方核心服务器有5GB 也就是40Gbps高防 军方无法突破此高防 请求你帮助，万分感谢！而且，敌方WAF反CC极强，敌人的后端代码也具有较强的抗CC能力，所以我无法通过CC攻击对敌人进行打击

# 我非常希望你能帮助，万分感谢！Dankeschön!

**Comment by xianquu** [comment]
![IMG_2525](https://github.com/luyii-code-1/rainyunautobat/assets/160004827/835d038b-327a-42d8-99cb-6638dd87715a)

**Comment by xianquu** [comment]
相关信息：https://bbs.deepin.org/post/272315

**Comment by luyii-code-1** [comment]
平台要求提供身份证人像面才能攻击，发到root@luyii.cn里来

**Comment by xianquu** [comment]
> 平台要求提供身份证人像面才能攻击，发到[root@luyii.cn](mailto:root@luyii.cn)里来

???不帮忙拉倒🌝

**Comment by luyii-code-1** [comment]
因为这个平台量很大（5mQps）
而且是正规压测平台
不给随便

**Comment by luyii-code-1** [comment]
另外，B站给我发消息

**Comment by xianquu** [comment]
> 另外，B站给我发消息

B站被你拉黑了🌝🌝

![IMG_2526](https://github.com/luyii-code-1/rainyunautobat/assets/160004827/1fd2dd66-6f25-4095-974e-7ca4b35a5c5d)

**Comment by xianquu** [comment]
![IMG_2527](https://github.com/luyii-code-1/rainyunautobat/assets/160004827/7b426e8c-d7da-43c0-b152-55d823377ce5)

我从来没听说过还有“正规压测平台” 还不如我自己轰炸呢🌝

**Comment by luyii-code-1** [comment]
那你自己去注册阿里云账号，压力测试服务新用户有免费额度，要实名

**Comment by xianquu** [comment]
> 那你自己去注册阿里云账号，压力测试服务新用户有免费额度，要实名

我怎么从来没听说过🌝而且未成年估计不能用阿里云

**Comment by luyii-code-1** [comment]
孤陋寡文
连阿里云注册实名机制都不知道

**Comment by xianquu** [comment]
我准备周末进行轰炸🌝敌人“欧阳云睿”（星火作者）狂妄自大，认为它们已经胜利了 呵呵🌝军方的战前准备基本完成，资本主义青年团安全局（情报部门）已经潜伏进入敌方QQ群  🌝另外 军方特种部队还对敌方某个广东高一小孩（只会python cpp Qt库 没什么本事的）进行了特别行动 行动暂时还没有见效🌝

**Comment by xianquu** [comment]
用阿里云压测了 轰炸敌方核心服务器毫无效果 全都被拦截了 （我把线程开到最大，并配合攻击平台，仅造成服务器卡顿，未完全倒闭）轰炸敌方沈阳放在敌人房子里的家用服务器成功 8000线程🌝证明了CC攻击完全行不通🌝阿里云还欠费了🌝
![IMG_2569](https://github.com/luyii-code-1/rainyunautobat/assets/160004827/9ed7085a-5c54-4b80-a9c0-1997aa87c678)
![IMG_2574](https://github.com/luyii-code-1/rainyunautobat/assets/160004827/1817cf49-11bc-4769-9b52-ccbe643c241e)
![IMG_2570](https://github.com/luyii-code-1/rainyunautobat/assets/160004827/3170049e-2c97-471c-aef5-aec45d20269a)
![IMG_2561](https://github.com/luyii-code-1/rainyunautobat/assets/160004827/55c295ee-a9a0-4ea8-bb41-bc7d78e5287c)

**Comment by xianquu** [comment]
我还有一个终极计划（军事绝密） 如果那个计划也失败，“资本主义青年团 VS 星火商店”战争就战败了🌝
